services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root  # Memberikan izin akses root agar bisa membaca docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Jembatan penghubung ke Docker Host
    restart: unless-stopped

volumes:
  jenkins_home: